### ISSUE TITLE
Pandas 2.0 removing `append`

### ISSUE THREAD

**Issue by billetd** [klaundal/lompe#31]
Just tagging this as I ran into when doing the default pip install of Lompe.

The current version of pandas installed using pip is greater than 2.0, which means `append` has been fully removed rather than just depreciated (https://pandas.pydata.org/docs/dev/whatsnew/v2.0.0.html). This threw up an error immediately when trying to use the `read_sdarn` pre-process script at L498. I got passed this by installing an older version of pandas (1.5.3 in my case), but the issue can also be resolved by using the pandas `concat` function everywhere `append` was used.

**Comment by jpreistad** [comment]
Thank you for pointing this out! Using `concat` sounds like a good strategy here, as you suggest. This should be a fairly straightforward fix to implement when one of us finds the time 👍
